### PR TITLE
cart endpoints

### PR DESCRIPTION
**Pull request by Jpickler**
DO NOT MERGE

### CODE REVIEW

**Comment by Jpickler** [comment]
DO NOT MERGE THIS

**Comment by trippolito** [comment]
maybe something like this to get a user's cart:
```
    async function getUserCart(user) {
      let userCart;
      userCart = await prisma.shoppingCart.findFirst({
        where: {
          user,
        },
        // include the list of cartCreatures in the response
        include: {
          cartCreature: true,
        },
      });
      if (!userCart) {
        userCart = await prisma.shoppingCart.create({
          data: {
            userId: user.id,
          }
        });
      }
      return userCart;
    }
```

**Comment by trippolito** [comment]
So to add a creature to your cart:

```
    async function addCartCreatureToCart(shoppingCart, creature, quantity = 1) {
      // find the creature in the shopping cart
      const cartCreature = await prisma.cartCreature.findFirst({
        where: {
          shoppingCartId: shoppingCart.id,
          creatureId: creature.id,
        },
      })
      // if there's already a creature of that type in the cart
      if (cartCreature) {
        // add the quantity to the existing quantity
        await prisma.cartCreature.update({
          where: {
            id: cartCreature.id,
          },
          data: {
            quantity: cartCreature.quantity + quantity,
          }
        })
      } else {
        // create a new cart creature with the desired quantity
        await prisma.cartCreature.create({
          data: {
            shoppingCartId: shoppingCart.id,
            creatureId: creature.id,
            quantity,
          }
        })
      }
    }
```

**Comment by trippolito** [comment]
g2g

**Review by barrettxavier — APPROVED** [review]

**Pull request merged**
